"""Candidate Intelligence models — Ascendia enrichment tables.

These tables store extracted candidate intelligence from Ascendia profiles
and the alignment matches between candidates and company organizational pain.

IMPORTANT: These are enrichment tables only. They never overwrite Ascendia
source tables (profiles, work_experience, accomplishments, etc.).
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, String, DateTime, Text, ForeignKey, Boolean, Integer, Float, text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from app.db.base import Base


class CandidateIntelligenceProfile(Base):
    """Extracted intelligence from an Ascendia candidate profile.

    Built by the CandidateIntelligenceExtractor which reads accomplishments,
    work experience, and other profile data to infer solved-pain categories
    and positioning vectors.
    """
    __tablename__ = "candidate_intelligence_profiles"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), unique=True, nullable=False, index=True)

    # Extracted capabilities
    dominant_capabilities = Column(JSONB, nullable=True, default=list)
    solved_pain_categories = Column(JSONB, nullable=True, default=list)

    # Strength dimensions (0.0-1.0 each)
    transformation_strength = Column(Float, nullable=True, default=0.0)
    analytics_strength = Column(Float, nullable=True, default=0.0)
    leadership_strength = Column(Float, nullable=True, default=0.0)
    operational_strength = Column(Float, nullable=True, default=0.0)
    modernization_strength = Column(Float, nullable=True, default=0.0)

    # Positioning
    inferred_positioning = Column(Text, nullable=True)
    positioning_vectors = Column(JSONB, nullable=True, default=list)

    # Alignment candidates (pre-computed list of company_ids with high fit)
    alignment_candidates = Column(JSONB, nullable=True, default=list)

    # Source metadata
    source_accomplishments_count = Column(Integer, nullable=True, default=0)
    source_experience_count = Column(Integer, nullable=True, default=0)
    extraction_version = Column(String, nullable=True, default="1.0.0")

    updated_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
        onupdate=lambda: datetime.now(timezone.utc),
    )
    created_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )


class FrictionCompanyProfile(Base):
    """FrictionRadar enrichment of a company — injected into Ascendia.

    Contains the organizational pain intelligence that FrictionRadar
    has detected for a company, formatted for candidate-facing consumption.
    """
    __tablename__ = "friction_company_profiles"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE"), unique=True, nullable=False, index=True)

    # Pain summary
    dominant_pain = Column(Text, nullable=True)
    pain_dimensions = Column(JSONB, nullable=True, default=dict)
    pain_clarity = Column(String, nullable=True)
    diagnostic_state = Column(String, nullable=True)

    # Positioning guidance
    recommended_positioning = Column(Text, nullable=True)
    candidate_archetype = Column(String, nullable=True)
    positioning_angle = Column(Text, nullable=True)
    resume_emphasis = Column(JSONB, nullable=True, default=list)
    networking_angle = Column(Text, nullable=True)
    interview_themes = Column(JSONB, nullable=True, default=list)

    # Evidence
    confidence_band = Column(String, nullable=True)
    evidence_depth = Column(JSONB, nullable=True, default=dict)

    # Temporal
    temporal_status = Column(String, nullable=True)
    trend_direction = Column(String, nullable=True)

    updated_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
        onupdate=lambda: datetime.now(timezone.utc),
    )
    created_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )


class FrictionCandidateMatch(Base):
    """Match between a candidate and a company's organizational pain.

    Generated by the Alignment Engine.
    """
    __tablename__ = "friction_candidate_matches"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)

    alignment_score = Column(Float, nullable=False, default=0.0)
    strategic_fit = Column(Text, nullable=True)
    positioning_recommendation = Column(Text, nullable=True)
    interview_positioning = Column(Text, nullable=True)
    resume_emphasis = Column(JSONB, nullable=True, default=list)
    networking_guidance = Column(Text, nullable=True)

    # What pain the candidate aligns with
    matched_pain_categories = Column(JSONB, nullable=True, default=list)
    matched_strengths = Column(JSONB, nullable=True, default=list)

    # Computation metadata
    computed_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )
    computation_version = Column(String, nullable=True, default="1.0.0")

    created_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )


class FrictionPositioningRecommendation(Base):
    """Detailed positioning recommendation for a candidate-company pair.

    More detailed than FrictionCandidateMatch — includes narrative guidance
    for VIP users.
    """
    __tablename__ = "friction_positioning_recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)

    # Core recommendation
    why_you_fit = Column(Text, nullable=True)
    why_they_value_you = Column(Text, nullable=True)
    positioning_summary = Column(Text, nullable=True)
    suggested_resume_emphasis = Column(JSONB, nullable=True, default=list)
    networking_positioning = Column(Text, nullable=True)
    interview_positioning = Column(Text, nullable=True)

    # Organizational pain context
    company_pain_summary = Column(Text, nullable=True)

    generated_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )
    created_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )


class FrictionVipOpportunity(Base):
    """VIP opportunity — differentiated for Ascendia VIP users.

    High-alignment matches surfaced as opportunities for VIP subscribers.
    """
    __tablename__ = "friction_vip_opportunities"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)

    alignment_score = Column(Float, nullable=False, default=0.0)
    opportunity_type = Column(String, nullable=True)  # early_positioning, accelerated_positioning, stable_fit
    company_pain_summary = Column(Text, nullable=True)
    strategic_positioning = Column(Text, nullable=True)
    resume_emphasis = Column(JSONB, nullable=True, default=list)
    networking_positioning = Column(Text, nullable=True)
    interview_positioning = Column(Text, nullable=True)
    why_you_fit = Column(Text, nullable=True)
    why_they_value_you = Column(Text, nullable=True)

    is_active = Column(Boolean, nullable=True, default=True, index=True)

    generated_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )
    created_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )


class FrictionAlignmentScore(Base):
    """Pre-computed alignment scores for efficient lookup.

    Denormalized score table for fast candidate-company alignment queries.
    """
    __tablename__ = "friction_alignment_scores"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)

    overall_score = Column(Float, nullable=False, default=0.0)
    pain_category_scores = Column(JSONB, nullable=True, default=dict)
    strength_category_scores = Column(JSONB, nullable=True, default=dict)

    computed_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )
    created_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )


class FrictionTemporalSnapshot(Base):
    """Temporal snapshot for tracking pain evolution over time.

    Each row captures the state of a company's pain at a point in time,
    enabling trend analysis and temporal intelligence.
    """
    __tablename__ = "friction_temporal_snapshots"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)

    snapshot_date = Column(DateTime(timezone=True), nullable=False, index=True)
    dominant_friction_type = Column(String, nullable=True)
    total_score = Column(Float, nullable=True)
    category_scores = Column(JSONB, nullable=True, default=dict)
    diagnostic_state = Column(String, nullable=True)
    pain_clarity = Column(String, nullable=True)
    hiring_pressure = Column(String, nullable=True)
    signal_count = Column(Integer, nullable=True, default=0)
    classified_roles_count = Column(Integer, nullable=True, default=0)

    snapshot_run_id = Column(String, nullable=True)

    created_at = Column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc), server_default=text("now()"),
    )